# Preload the wallpaper
preload = /home/shvnix/Pictures/Wallpapers/1324528.jpeg

# Set wallpaper for all monitors
wallpaper = ,/home/shvnix/Pictures/Wallpapers/1324528.jpeg

# Optional: disable splash
splash = false

