# ===========================================
# Hyprpaper
# Fedora Hyprland Workstation
# ===========================================

preload = ~/Pictures/Wallpapers/1324528.jpeg

wallpaper = ,/home/shvnix/Pictures/Wallpapers/1324528.jpeg

splash = false
