# ===========================================
# Hyprpaper
# Fedora Hyprland Workstation
# ===========================================

preload = /usr/local/share/fedora-hyprland-workstation/wallpapers/1324528.jpeg

wallpaper = ,/usr/local/share/fedora-hyprland-workstation/wallpapers/1324528.jpeg

splash = false
