##############################################
# Input Configuration
##############################################

input {

    kb_layout = us

    follow_mouse = 1

    sensitivity = 0

    touchpad {

        natural_scroll = true

        tap-to-click = true

        disable_while_typing = true

        clickfinger_behavior = true

    }

}

##############################################
# Touchpad Gestures
##############################################

gestures {
    workspace_swipe_distance = 300
    workspace_swipe_invert = true
}

gesture = 3, horizontal, workspace

