##############################################
# Startup Applications
##############################################

# Authentication agent
exec-once = /usr/libexec/polkit-gnome-authentication-agent-1

# Wayland clipboard support
exec-once = wl-paste --type text --watch cliphist store

# Notification daemon
exec-once = mako

# Status bar
exec-once = waybar

# Wallpaper
exec-once = hyprpaper

