##############################################
# Variables
##############################################

# Main modifier key.
# SUPER = Windows key.
$mainMod = SUPER

# Preferred terminal.
$terminal = kitty

# Application launcher.
$menu = wofi --show drun

# File manager.
$fileManager = thunar
