##############################################
# Window Rules
##############################################

# Float file chooser dialogs
windowrulev2 = float,class:^(xdg-desktop-portal-gtk)$

# Float authentication dialogs
windowrulev2 = float,class:^(polkit-gnome-authentication-agent-1)$

# Float picture-in-picture
windowrulev2 = float,title:^(Picture-in-Picture)$

# Float pavucontrol
windowrulev2 = float,class:^(pavucontrol)$



##############################################
# Android Emulator
##############################################

# Always float
windowrulev2 = float,class:^(Emulator)$

# Open centered
windowrulev2 = center,class:^(Emulator)$

# Set default size (adjust to your preference)
windowrulev2 = size 450 900,class:^(Emulator)$


